$(document).ready(function(){
    $(".al").click(function(){
        window.location.href="alert.html";
    })
    $(".arg").click(function(){
        window.location.href="arguement.html";
    })
    $(".att").click(function(){
        window.location.href="attribute.html";
    })
    $(".boo").click(function(){
        window.location.href="boolean.html";
    })
    $(".cha").click(function(){
        window.location.href="chainingmethod.html";
    })
    $(".com").click(function(){
        window.location.href="comment.html";
    })
    $(".fun").click(function(){
        window.location.href="function.html";
    })
    $(".js").click(function(){
        window.location.href="javascript.html";
    })
    $(".jq").click(function(){
        window.location.href="jquery.html";
    })
    $(".met").click(function(){
        window.location.href="method.html";
    })
    $(".na").click(function(){
        window.location.href="nan.html";
    })
    $(".nu").click(function(){
        window.location.href="null.html";
    })
    $(".ope").click(function(){
        window.location.href="operator.html";
    })
    $(".par").click(function(){
        window.location.href="parameter.html";
    })
    $(".ret").click(function(){
        window.location.href="return.html";
    })
    $(".str").click(function(){
        window.location.href="string.html";
    })
    $(".syn").click(function(){
        window.location.href="syntax.html";
    })
    $(".und").click(function(){
        window.location.href="undefined.html";
    })
    $(".vn").click(function(){
        window.location.href="variablenames.html";
    })
    $(".var").click(function(){
        window.location.href="variables.html";
    })
})